name: Catalogue

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

jobs:
  payment:
    name: Build and deploy catalogue microservice
    runs-on: ubuntu-latest  # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Adjust to your project's Node.js version


      - name: NPM install
        working-directory: ./catalogue
        run: npm install 

      - name: Build Docker image
        working-directory: ./catalogue
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:latest .  # Build image tagged as 'payment' from current directory

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:latest