name: Dispatch

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '.github/workflows/dispatch.yaml'

  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - '.github/workflows/dispatch.yaml'

jobs:
  dispatch:
    name: Build and deploy dispatch microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          docker --version

      - name: Build Docker image
        working-directory: ./dispatch
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dispatch:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dispatch:latest
